"""
gen-ddl.py — Generate DDL SQL from a data dictionary JSON specification.

Usage:
    python gen-ddl.py --input data-dictionary.json --output db-schema.sql

The input JSON should conform to the db_schema.json schema.
"""

import json
import argparse
from typing import Any


TYPE_MAPPING = {
    "uuid": "UUID",
    "varchar": "VARCHAR",
    "text": "TEXT",
    "integer": "INTEGER",
    "bigint": "BIGINT",
    "boolean": "BOOLEAN",
    "timestamp": "TIMESTAMP",
    "jsonb": "JSONB",
    "decimal": "DECIMAL",
}


def map_type(col_type: str) -> str:
    mapped = TYPE_MAPPING.get(col_type.lower(), col_type.upper())
    return mapped


def generate_create_table(table: dict[str, Any]) -> str:
    name = table["name"]
    lines = [f"CREATE TABLE IF NOT EXISTS {name} ("]
    col_defs = []

    for col in table.get("columns", []):
        col_def = f"    {col['name']} {map_type(col['type'])}"
        if not col.get("nullable", True):
            col_def += " NOT NULL"
        if col.get("default"):
            col_def += f" DEFAULT {col['default']}"
        if col.get("unique"):
            col_def += " UNIQUE"
        col_defs.append(col_def)

    if "primary_key" in table:
        pk = ", ".join(table["primary_key"])
        col_defs.append(f"    PRIMARY KEY ({pk})")

    lines.append(",\n".join(col_defs))
    lines.append(");")

    return "\n".join(lines)


def generate_indexes(table: dict[str, Any]) -> list[str]:
    statements = []
    name = table["name"]

    for idx in table.get("indexes", []):
        cols = ", ".join(idx["columns"])
        unique = "UNIQUE " if idx.get("unique") else ""
        stmt = f"CREATE {unique}INDEX IF NOT EXISTS {idx['name']} ON {name} ({cols});"
        statements.append(stmt)

    return statements


def generate_foreign_keys(relationships: list[dict[str, Any]]) -> list[str]:
    statements = []
    for rel in relationships:
        stmt = (
            f"ALTER TABLE {rel['from_table']} "
            f"ADD CONSTRAINT fk_{rel['from_table']}_{rel['foreign_key_column']} "
            f"FOREIGN KEY ({rel['foreign_key_column']}) "
            f"REFERENCES {rel['to_table']}(id) "
            f"ON DELETE {rel.get('on_delete', 'CASCADE')};"
        )
        statements.append(stmt)
    return statements


def generate_ddl(spec: dict[str, Any]) -> str:
    parts = [
        "-- ============================================",
        f"-- DDL for: {spec.get('project', 'untitled')}",
        f"-- Generated by Harness Data Model",
        "-- ============================================",
        "",
    ]

    for table in spec.get("tables", []):
        parts.append(f"-- Table: {table['name']}")
        parts.append(generate_create_table(table))
        parts.append("")

        for idx_stmt in generate_indexes(table):
            parts.append(idx_stmt)
            parts.append("")

    if spec.get("relationships"):
        parts.append("-- Foreign Key Relationships")
        for fk_stmt in generate_foreign_keys(spec["relationships"]):
            parts.append(fk_stmt)
        parts.append("")

    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser(description="Generate DDL SQL from data dictionary JSON")
    parser.add_argument("--input", "-i", required=True, help="Input JSON file path")
    parser.add_argument("--output", "-o", required=True, help="Output SQL file path")
    args = parser.parse_args()

    with open(args.input, "r", encoding="utf-8") as f:
        spec = json.load(f)

    ddl = generate_ddl(spec)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(ddl)

    print(f"DDL written to {args.output}")


if __name__ == "__main__":
    main()
